name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t tank-game:test .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: tank-game:test
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH