name: Trigger auto deployment for tank-game-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tank-game-app-AutoDeployTrigger-95814aed-8445-46f6-bb4b-f2ea6ba5b4c1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TANKGAMEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TANKGAMEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TANKGAMEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: tankgameregistry.azurecr.io
          registryUsername: ${{ secrets.TANKGAMEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TANKGAMEAPP_REGISTRY_PASSWORD }}
          containerAppName: tank-game-app
          resourceGroup: Demo-Cloud-Native
          imageToBuild: tankgameregistry.azurecr.io/tank-game-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


